name: Second Workflow

on:
  workflow_run:
    workflows: ["A workflow for my Hello World file"]
    branches: [master]
    types: 
      - completed

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Daniel"
